### ISSUE TITLE
ProMicro RX/TX LEDs

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/FABI#13]
When using the Bluetooth Addon, its LED is not clearly visible compared to the Arduino Pro Micro's RX/TX LEDs.

Should we switch off these LEDs?

```
pinMode(LED_BUILTIN_RX,INPUT);
pinMode(LED_BUILTIN_TX,INPUT);
```

**Comment by ChrisVeigl** [comment]
done! 
I also removed the internal LED blinking at startup ...
