### ISSUE TITLE
Button Action: Changing between Tabs deletes previous value

### ISSUE THREAD

**Issue by deinhofer** [asterics/FABI#31]
When opening the action of a button to (re)configure it, the currently set value is deleted as soon as you change the tab (e.g. from Mouse to Keyboard) and back again:

![grafik](https://user-images.githubusercontent.com/4621810/146185099-5e923173-0f6a-4a20-b9f4-a732d0f9c3fd.png)

This is annoying as sometimes you only want to check other options.

**Comment by ChrisVeigl** [comment]
but this only happens if do do not _save_ the changes ..
why would you switch tabs without saving and then expect the values to remain the same ?

**Comment by klues** [comment]
I agree, when switchung between the categories and nothing was changed yet, the current value should be selected, if available in the current category. I'll fix it.

**Comment by klues** [comment]
For "current value" i would understand the value currently stored in the FLipMouse, not the value I've possibly selected in the GUI before switching categories without saving.

**Comment by deinhofer** [comment]
> For "current value" i would understand the value currently stored in the FLipMouse, not the value I've possibly selected in the GUI before switching categories without saving.

Yes, I agree. It should always be in sync with the currently stored value as long as no new one was selected or saved.

**Comment by deinhofer** [comment]
> but this only happens if do do not _save_ the changes .. why would you switch tabs without saving and then expect the values to remain the same ?

because you have to open the dialog and switch the tabs to see all possible actions, when you switch back you currently saved setting is gone. This is confusing, if you don't know the old value any more and you don't know that cancelling the dialog brings back the old value.

**Comment by klues** [comment]
fixed with https://github.com/asterics/Addon-Bluetooth-WebGUI/commit/d50f7f28c21ee1daa5a362b2f63783d8b2037984
Reload `fabi.asterics.eu` twice or use `Ctrl + F5` to reload before testing in order to clear/update local offline cache.
